name: HyPER
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - cxx-compiler
  - python=3.10.*
  - pip
  - pytorch=2.3.*
  - pytorch-cuda=11.8
  - torchvision
  - torchaudio
  - pip:
    - torch_geometric
    - torch_scatter --find-links https://data.pyg.org/whl/torch-2.3.0+cu118.html
    - numpy=1.26.4
    - pandas
    - lightning
    - pytorch-lightning
    - tensorboard
    - jupyterlab
    - uproot
    - awkward
    - h5py
    - pylorentz
    - torch-hep==0.0.4
    - hydra-core
    - rich
    - onnx
    - onnxruntime
    - onnxscript
