name: HyPER
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch=2.2.2
  - torchvision=0.17.2
  - torchaudio=2.2.2
  - pip:
    - torch_geometric==2.5.3
    - torch_scatter==2.1.2
    - torch_sparse==0.6.18
    - torch_cluster==1.6.3
    - torch_spline_conv==1.2.2
    - numpy==1.26.4
    - pandas==2.2.2
    - lightning==2.2.3
    - pytorch-lightning==2.2.3
    - tensorboard==2.16.2
    - jupyterlab==4.1.6
    - uproot==5.3.3
    - awkward==2.6.3
    - h5py==3.11.0
    - pylorentz==0.3.3
    - torch-hep==0.0.4
    - hydra-core==1.3.2
    - rich==13.7.1
    - onnx==1.16.0
    - onnxruntime==1.17.3
    - onnxscript==0.1.0.dev20240421