name: HyPER
channels:
  - pytorch
dependencies:
  - python=3.10.*
  - pip
  - pytorch=2.5.*
  - torchvision
  - torchaudio
  - pip:
    - torch_geometric
    - https://data.pyg.org/whl/torch-2.5.0%2Bcpu/torch_scatter-2.1.2-cp310-cp310-macosx_10_9_universal2.whl
    - numpy==1.26.4
    - pandas
    - lightning==2.5.*
    - tensorboard
    - jupyterlab
    - uproot
    - awkward
    - h5py
    - torch-hep==0.0.4
    - hydra-core
    - rich
    - onnx
    - onnxruntime==1.18
    - onnxscript
