input:
  padding: 24 #20 jets + 3 leptons + 1 MET
  nodes: # of form {Node type: enum}. Lists each object as defined in the "INPUTS" group of the h5 files, with an enum which the user can define, and which HyPER use as a node feature
    JET: 1
    #LEPTON: 2
    #MET: 3
  node_features: # Ordered list of node features - although should change such that doesn't need to be in this order
    - e
    - eta
    - phi 
    - pt 
  node_transforms: # Corresponding list of transformations to the node features
    - torch.log(x)
    - x
    - x
    - torch.log(x)
  edge_features: # List of edge features from a pre-defined list of edge features which HyPER can construct
    - delta_eta
    - delta_phi
    - delta_R
    - M2
  global_features: # Global feature list
    - njet
  global_transforms: # Corresponding list of transformations to the global data
    - x/6
  pre_transform: True # Boolean whether to transform the features before saving the dataset PyG object to file

target: 
# Nodes are of the form [particle_enum - matching index]. particle_enum corresponds to the values of the nodes field above. 
  edge:
    w1: ['1-2','1-3']
    w2: ['1-5','1-6']
  hyperedge: 
    t1: ['1-1','1-2','1-3']
    t2: ['1-4','1-5','1-6']